[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
avian3d.workspace = true

nevy.workspace = true
rustls = { version = "0.23.5", default-features = false, features = ["std"] }
rustls-pemfile = "2.1.2"

common.path = "../common"
